#spring.application.name=board
spring:
  #  ??? jdbc?? db?? ??? jdbc?? ??? mybatis, jpa? ?? ??? ??? ??.
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3307/basic
    username: junseo
    password: 1234
  jpa:
    database: mysql
    #    innoDB?? ??
    database-platform: org.hibernate.dialect.MariaDBDialect
    #    ddl? ????. ???? ????(??)???, ???? ??? ??? ????
    generate-ddl: true  #ddl auto ??.
    #    jpa? ???????, hibernate? jpa? ???? ???(???? ?? ??)
    hibernate:
      #      create : ?? table? drop ? ???
      #      update : entity????? alter? ???? ????? ??.(?? ????? alter?? ?? ?? - ??? ?? ??? ??.)
      #      validate : ??DB?? ???? check?? ???? ??.
      ddl-auto: create
    #      ???? ddl, dml?? ???? ???? ??
    show_sql: true